apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: web # Asegúrate de que este namespace exista o cámbialo al namespace que estás usando
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'flask_app'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: web-service