apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: microservices-ci
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: carlosdelgadillo/web:v3
        ports:
        - containerPort: 9000
        env:
        - name: URL_SUMAR
          value: "http://192.168.49.2:30655/sumar"  # Reemplaza con la dirección del servicio de suma
        - name: URL_RESTAR
          value: "http://192.168.49.2:32543/restar"  # Reemplaza con la dirección del servicio de resta
        - name: URL_MULTIPLICAR
          value: "http://192.168.49.1:8003/multiply"  # Reemplaza con la dirección del servicio de multiplicar
        - name: URL_DIVIDIR
          value: "http://192.168.49.2:32324/divide"  # Reemplaza con la dirección del servicio de dividir
        - name: PUERTO
          value: "9000"  # El puerto en el que correrá tu aplicación


